volumes:
  pg_data:

services:
  db:
    container_name: postgres
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  python:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
