version: '3.7'

volumes:
  pg_data:

services:
  db:
    container_name: postgres
    image: postgres:16
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ubuntu
      POSTGRES_PASSWORD: pw_ubuntu
      POSTGRES_DB: top_content
  python:
    build:
      context: .
      dockerfile: ./docker/Dockerfile

    depends_on:
      - db
